version: '3'

services:
  api:
    build: ./api
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - ./api/resnet50-11ad3fa6.pth:/app/resnet50-11ad3fa6.pth
      - ./client/test:/app/test
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health_check"]
      interval: 30s
      timeout: 10s
      retries: 5
      

  client:
    build: ./client
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - ./client:/app
      - ./client/test:/app/test
